version: "3.8"
services:
  prisma-db:
    image: postgres:15
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: prisma
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
